import jsPDF from 'jspdf';
import { ScheduleItem } from '../types/mortgage';

// Real PDF export using jsPDF
export const exportToPDF = (data: {
  homeValue: number;
  downPayment: number;
  loanAmount: number;
  interestRate: number;
  tenure: number;
  paymentAmount: number;
  totalInterest: number;
  totalPaid: number;
  endDate: string;
  schedule: ScheduleItem[];
  currency?: string;
  propertyTax?: number;
  insurance?: number;
}) => {
  const currencySymbol = data.currency || '$';
  const doc = new jsPDF();
  
  // Set font
  doc.setFont('helvetica');
  
  // Title
  doc.setFontSize(20);
  doc.setTextColor(30, 58, 138); // Blue color
  doc.text('Mortgage Calculator Report', 105, 20, { align: 'center' });
  
  // Date
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 105, 28, { align: 'center' });
  
  // Loan Details Section
  let y = 45;
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.text('Loan Details', 20, y);
  
  y += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Home Value: ${currencySymbol}${data.homeValue.toLocaleString()}`, 20, y);
  y += 7;
  doc.text(`Down Payment: ${currencySymbol}${data.downPayment.toLocaleString()}`, 20, y);
  y += 7;
  doc.text(`Loan Amount: ${currencySymbol}${data.loanAmount.toLocaleString()}`, 20, y);
  y += 7;
  doc.text(`Interest Rate: ${data.interestRate.toFixed(3)}%`, 20, y);
  y += 7;
  doc.text(`Loan Term: ${data.tenure} years`, 20, y);
  
  // Payment Summary Section
  y += 15;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Payment Summary', 20, y);
  
  y += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Monthly Payment: ${currencySymbol}${data.paymentAmount.toLocaleString()}`, 20, y);
  y += 7;
  doc.text(`Total Interest: ${currencySymbol}${data.totalInterest.toLocaleString()}`, 20, y);
  y += 7;
  doc.text(`Total Paid: ${currencySymbol}${data.totalPaid.toLocaleString()}`, 20, y);
  y += 7;
  doc.text(`Payoff Date: ${data.endDate}`, 20, y);
  
  // Additional Costs (if any)
  if (data.propertyTax || data.insurance) {
    y += 15;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Additional Costs', 20, y);
    
    y += 10;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    if (data.propertyTax) {
      doc.text(`Property Tax: ${currencySymbol}${data.propertyTax.toLocaleString()}/year`, 20, y);
      y += 7;
    }
    if (data.insurance) {
      doc.text(`Insurance: ${currencySymbol}${data.insurance.toLocaleString()}/year`, 20, y);
      y += 7;
    }
  }
  
  // Amortization Schedule Section
  y += 15;
  if (y > 250) {
    doc.addPage();
    y = 20;
  }
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Amortization Schedule (First 12 Payments)', 20, y);
  
  y += 10;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  
  // Table header
  doc.text('Payment', 20, y);
  doc.text('Date', 40, y);
  doc.text('Principal', 70, y);
  doc.text('Interest', 100, y);
  doc.text('Balance', 130, y);
  
  y += 5;
  doc.setFont('helvetica', 'normal');
  
  // Table rows (first 12 payments)
  const displaySchedule = data.schedule.slice(0, 12);
  for (const item of displaySchedule) {
    if (y > 280) {
      doc.addPage();
      y = 20;
      
      // Repeat header on new page
      doc.setFont('helvetica', 'bold');
      doc.text('Payment', 20, y);
      doc.text('Date', 40, y);
      doc.text('Principal', 70, y);
      doc.text('Interest', 100, y);
      doc.text('Balance', 130, y);
      y += 5;
      doc.setFont('helvetica', 'normal');
    }
    
    doc.text(`#${item.paymentNum}`, 20, y);
    doc.text(item.date, 40, y);
    doc.text(`${currencySymbol}${Math.round(item.principal).toLocaleString()}`, 70, y);
    doc.text(`${currencySymbol}${Math.round(item.interest).toLocaleString()}`, 100, y);
    doc.text(`${currencySymbol}${Math.round(item.balance).toLocaleString()}`, 130, y);
    y += 6;
  }
  
  // Footer note
  y += 5;
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(`... ${data.schedule.length - 12} more payments`, 20, y);
  
  // Add footer with URL
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('Generated by Mortgage Calculator', 105, 285, { align: 'center' });
    doc.text('https://mortgage-calculator-kappa-nine.vercel.app/', 105, 290, { align: 'center' });
  }
  
  // Save the PDF
  doc.save(`mortgage-report-${new Date().toISOString().split('T')[0]}.pdf`);
};
